stages:
  - development
  - build
install node:
    image: node:18.17.1
    stage: development
    script:
        - npm ci
build the application:
    image: node:18:17.1
    stage: build
    script:
        - npm ci
        - npm run build
    artifacts:
        paths:
            - build

