name: Testing with jest

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: disable
        run: |
          npx next telemetry status
          npx next telemetry disable

    - name: Build
      run: |
        npx next telemetry status
        npx next telemetry disable
        npm install
        npx next telemetry status
        npx next telemetry disable
        npm run build
        npx next telemetry status
        npx next telemetry disable
